apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
spec:
  project: frontend-team
  source:
    repoURL: https://github.com/LondheShubham153/argocd-demos.git
    targetRevision: main
    path: app_of_apps/apps
  destination:
    server: <cluster_ip>
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
