apiVersion: v1 
kind: Secret   
metadata:
  name: argocd-notifications-secret  
  namespace: argocd                
type: Opaque  
stringData:   
  email-username: "your-email@example.com"   
  email-password: "your-smtp-password"       
